name: '998'
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - altair=5.0.1
  - annotated-types=0.6.0
  - anyio=4.2.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.1.0
  - aws-c-auth=0.7.25
  - aws-c-cal=0.7.3
  - aws-c-common=0.9.27
  - aws-c-compression=0.2.19
  - aws-c-event-stream=0.4.3
  - aws-c-http=0.8.7
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.4
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.6
  - aws-sdk-cpp=1.11.379
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.2
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.7.2
  - cachetools=5.3.3
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - comm=0.2.1
  - dataclasses=0.8
  - dataclasses-json=0.6.5
  - datasets=2.19.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - distro=1.9.0
  - executing=0.8.3
  - faiss=1.8.0
  - faker=28.0.0
  - filelock=3.13.1
  - flask=3.0.3
  - flask-cors=4.0.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2024.3.1
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glog=0.7.1
  - greenlet=3.0.1
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - huggingface_hub=0.24.6
  - icu=75.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib_resources=6.4.0
  - ipykernel=6.28.0
  - ipython=8.25.0
  - ipywidgets=8.1.2
  - itsdangerous=2.2.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - json5=0.9.6
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.10
  - krb5=1.21.3
  - langchain=0.2.14
  - langchain-community=0.2.12
  - langchain-core=0.2.35
  - langchain-experimental=0.0.64
  - langchain-text-splitters=0.2.2
  - langsmith=0.1.104
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.9.1
  - libcxx=18.1.8
  - libdeflate=1.20
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libfaiss=1.8.0
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgoogle-cloud=2.28.0
  - libgoogle-cloud-storage=2.28.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.21
  - libparquet=17.0.0
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libthrift=0.20.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - marshmallow=3.19.0
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mistune=2.0.4
  - multidict=6.0.4
  - multiprocess=0.70.15
  - mypy_extensions=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openai=1.37.0
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=2.0.2
  - orjson=3.9.15
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=4.25.3
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pycparser=2.21
  - pydantic=2.5.3
  - pydantic-core=2.14.6
  - pydeck=0.8.0
  - pygments=2.15.1
  - pypdf2=3.0.1
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python_abi=3.11
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qtconsole-base=5.5.2
  - qtpy=2.4.1
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.7.24
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.10.6
  - safetensors=0.4.2
  - send2trash=1.8.2
  - setuptools=72.1.0
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlalchemy=2.0.30
  - stack_data=0.2.0
  - streamlit=1.37.1
  - tenacity=8.2.3
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - tokenizers=0.19.1
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - transformers=4.44.2
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_inspect=0.9.0
  - tzdata=2024a
  - tzlocal=5.2
  - urllib3=2.2.2
  - validators=0.18.2
  - watchdog=4.0.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.3
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.5
  - zipp=3.17.0
  - zstd=1.5.6
  - pip:
      - annoy==1.17.3
      - azure-core==1.30.2
      - blis==0.7.11
      - catalogue==2.0.10
      - cloudpathlib==0.18.1
      - coloredlogs==15.0.1
      - confection==0.1.5
      - cymem==2.0.8
      - en-core-web-lg==3.7.1
      - fastapi==0.112.2
      - fastembed==0.3.6
      - flatbuffers==24.3.25
      - humanfriendly==10.0
      - langcodes==3.4.0
      - language-data==1.2.0
      - lark==1.1.9
      - loguru==0.7.2
      - marisa-trie==1.2.0
      - mmh3==4.1.0
      - mpmath==1.3.0
      - murmurhash==1.0.10
      - nemoguardrails==0.9.1.1
      - onnx==1.16.2
      - onnxruntime==1.19.0
      - phonenumbers==8.13.44
      - pillow==10.4.0
      - preshed==3.0.9
      - presidio-analyzer==2.2.355
      - presidio-anonymizer==2.2.355
      - pycryptodome==3.20.0
      - pystemmer==2.2.0.1
      - requests-file==2.1.0
      - shellingham==1.5.4
      - simpleeval==0.9.13
      - smart-open==7.0.4
      - snowballstemmer==2.2.0
      - spacy==3.7.6
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - starlette==0.38.2
      - sympy==1.13.2
      - thinc==8.2.5
      - tldextract==5.1.2
      - typer==0.12.5
      - uvicorn==0.30.6
      - wasabi==1.1.3
      - weasel==0.4.1
      - wrapt==1.16.0
